2020-03-06 00:54:22,592 - instabot version: 0.112.0 (bot) - INFO - Instabot version: 0.112.0 Started
2020-03-06 00:54:22,592 - instabot version: 0.112.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-06 00:54:39,862 - instabot version: 0.112.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-06 00:54:41,101 - instabot version: 0.112.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-03-06 00:54:41,526 - instabot version: 0.112.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-03-06 00:54:43,084 - instabot version: 0.112.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-03-06 00:54:44,079 - instabot version: 0.112.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-03-06 00:54:46,099 - instabot version: 0.112.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-06 00:54:46,100 - instabot version: 0.112.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/27776086740/3uKqebjfx9/", "api_path": "/challenge/27776086740/3uKqebjfx9/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}
2020-03-06 00:54:46,100 - instabot version: 0.112.0 (api) - ERROR - Request returns 400 error!
2020-03-06 00:54:46,100 - instabot version: 0.112.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-06 00:54:46,101 - instabot version: 0.112.0 (api) - INFO - Error type: checkpoint_challenge_required
2020-03-06 00:54:46,101 - instabot version: 0.112.0 (api) - CRITICAL - Not logged in!
